apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    service: mediawiki
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    service: mediawiki
